sudo: required
services:
  - docker

before_install:
  - docker build -t 4id3y/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 4id3y/docker-react npm run test -- --coverage

language: generic