sudo: required
services:
  - docker

before_install:
  - docker build -t 4id3y/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 4id3y/docker-react npm run test -- --coverage

language: generic

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-054978424145"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"



